language: c
sudo: false
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libgmp-dev
      - libgmp10
before_install:
  - sed -i -e 's|AC_PREREQ(2.69)|AC_PREREQ(2.68)|' configure.ac
script:
  - ./bootstrap && ./configure && make -j2 distcheck
